### ISSUE TITLE
Server deployment

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/WAM_APP_FRED#106]
Get everything running on Server. When cloning WAM_APP_FRED and scp-ing local geojson files, make sure django has the necessary reading permissions (chmod +r) for those files, otherwise it won't be able to find them. I've tested the following functions. No ✓ means, it's not working:

- [x] weather points
- [x] weather popups
- [x] powerplant points
- [x] powerplant popups
- [x] feedin points
- [x] feedin popups
- [x] bundesländer geojson
- [x] landkreise geojson
- [x] clustering

**Comment by christian-rli** [comment]
@Bachibouzouk I recall the weather-pop-ups not working on the server before. Do you have any idea, why this doesn't not seem to work on the server, while the other queries do work? Unfortunately I don't know who to show the django output on the server docker, but I'm going to research that now.
**update:** Docker remains a mystery to me, but Firefox told me that it's a 502 'bad gateway' error

**Comment by christian-rli** [comment]
Weather popup causes the following error on the webserver:
```

2019/07/24 06:55:54 [WARNING] Sending telemetry (attempt 1): telemetry server replied with unknown content-type: 'text/plain; charset=utf-8' and HTTP 502 Bad Gateway - backing off and retrying
2019/07/24 06:56:03 [WARNING] Sending telemetry (attempt 2): telemetry server replied with unknown content-type: 'text/plain; charset=utf-8' and HTTP 502 Bad Gateway - backing off and retrying
2019/07/24 06:56:30 [WARNING] Sending telemetry (attempt 3): telemetry server replied with unknown content-type: 'text/plain; charset=utf-8' and HTTP 502 Bad Gateway - backing off and retrying
2019/07/24 06:57:34 [ERROR] Sending telemetry: telemetry server replied with unknown content-type: 'text/plain; charset=utf-8' and HTTP 502 Bad Gateway
```

**Comment by christian-rli** [comment]
fred_app.cfg looks like this:

```
[WAM_APP_FRED]
        EGO_DP_VERSION=v0.4.5
        SCENARIO=Status Quo
        OEP_ACCESS=OEP_DIALECT
```
and OEP_DIALECT in config is the same as in my local setup.

**Comment by nesnoj** [comment]
The id seems to be the wrong type as wam logs says

```
Internal Server Error: /WAM_APP_FRED/WeatherPointClick.data/
Traceback (most recent call last):
  File "/opt/conda/envs/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/conda/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/conda/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/WAM_APP_FRED/serial_views.py", line 445, in wseries_fetch_data_single_point
    location_id = int(request.POST.get('location_id'))
ValueError: invalid literal for int() with base 10: 'find_something_unique'
```
This might be related?

**Comment by Bachibouzouk** [comment]
It could be, the 'find_something_unique' error should have been fixed in f0691a20b46fe364c11caad01b1e64a335f9deac from #109

**Comment by christian-rli** [comment]
> It could be, the 'find_something_unique' error should have been fixed in [f0691a2](https://github.com/rl-institut/WAM_APP_FRED/commit/f0691a20b46fe364c11caad01b1e64a335f9deac) from #109

Unfortunately this did not fix weather popups on the server.

**Comment by christian-rli** [comment]
Could it be possible that there is just a time-limit on our server that collides with the long loading times of our weather query?

**Comment by christian-rli** [comment]
@henhuy fixed the timeout issue in #61 by setting the limit up to 1 minute, thereby closing the last remaining issue in this list.
